export const TOOL_CONFIGS = {
  merge: {
    title: "Merge PDF",
    category: "Organize",
    multiFile: true,
    mode: "view",
    endpoint: "merge",
    filenameSuffix: "_merged",
    fields: [{ name: "filename", label: "Output filename", type: "text", default: "" }],
  },
  split: {
    title: "Split PDF",
    category: "Organize",
    multiFile: false,
    mode: "view",
    endpoint: "split",
    fields: [
      { name: "pages_per_file", label: "Pages per output file", type: "number", default: 1, min: 1 },
    ],
  },
  "remove-pages": {
    title: "Remove pages",
    category: "Organize",
    multiFile: false,
    mode: "select",
    endpoint: "remove-pages",
    fields: [],
  },
  "extract-pages": {
    title: "Extract pages",
    category: "Organize",
    multiFile: false,
    mode: "select",
    endpoint: "extract-pages",
    fields: [],
  },
  "reorder-pages": {
    title: "Reorder pages",
    category: "Organize",
    multiFile: false,
    mode: "reorder",
    endpoint: "reorder-pages",
    fields: [],
  },
  rotate: {
    title: "Rotate PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    endpoint: "rotate",
    fields: [
      { name: "angle", label: "Rotate by", type: "select", options: [90, 180, 270], default: 90 },
    ],
  },
  watermark: {
    title: "Add watermark",
    category: "Edit",
    multiFile: false,
    mode: "view",
    endpoint: "watermark",
    fields: [
      { name: "text", label: "Watermark text", type: "text", default: "" },
      {
        name: "opacity",
        label: "Opacity (%)",
        type: "range",
        min: 10,
        max: 100,
        default: 30,
        scale: 0.01,
      },
    ],
  },
  compress: {
    title: "Compress PDF",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    endpoint: "compress",
    fields: [
      { name: "image_quality", label: "Image quality", type: "range", min: 10, max: 100, default: 60 },
    ],
  },
  "to-images": {
    title: "PDF to Image",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "to-images",
    fields: [
      { name: "image_format", label: "Format", type: "select", options: ["jpg", "png"], default: "jpg" },
    ],
  },
  "to-word": {
    title: "PDF to Word",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "to-word",
    fields: [],
  },
};
