export const TOOL_CONFIGS = {
  merge: {
    title: "Merge PDF",
    category: "Organize",
    multiFile: true,
    mode: "view",
    preview: "merge",
    endpoint: "merge",
    filenameSuffix: "_merged",
    fields: [{ name: "filename", label: "Output filename", type: "text", default: "" }],
  },
  split: {
    title: "Split PDF",
    category: "Organize",
    multiFile: false,
    mode: "view",
    preview: "split",
    endpoint: "split",
    fields: [
      { name: "pages_per_file", label: "Pages per output file", type: "number", default: 1, min: 1 },
    ],
  },
  "remove-pages": {
    title: "Remove pages",
    category: "Organize",
    multiFile: false,
    mode: "select",
    endpoint: "remove-pages",
    fields: [],
  },
  "extract-pages": {
    title: "Extract pages",
    category: "Organize",
    multiFile: false,
    mode: "select",
    endpoint: "extract-pages",
    fields: [],
  },
  "reorder-pages": {
    title: "Reorder pages",
    category: "Organize",
    multiFile: false,
    mode: "reorder",
    endpoint: "reorder-pages",
    fields: [],
  },
  rotate: {
    title: "Rotate PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "rotate",
    endpoint: "rotate",
    fields: [
      { name: "angle", label: "Rotate by", type: "select", options: [90, 180, 270], default: 90 },
    ],
  },
  watermark: {
    title: "Add watermark",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "watermark",
    endpoint: "watermark",
    fields: [
      { name: "text", label: "Watermark text", type: "text", default: "" },
      {
        name: "opacity",
        label: "Opacity (%)",
        type: "range",
        min: 10,
        max: 100,
        default: 30,
        scale: 0.01,
      },
      {
        name: "font_size",
        label: "Font size (pt)",
        type: "range",
        min: 10,
        max: 120,
        default: 40,
      },
      {
        name: "rotate",
        label: "Rotation (degrees)",
        type: "range",
        min: 0,
        max: 360,
        default: 0,
      },
    ],
  },
  "add-page-numbers": {
    title: "Add page numbers",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "page-numbers",
    endpoint: "add-page-numbers",
    fields: [
      {
        name: "position",
        label: "Position",
        type: "select",
        options: [
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "top-left", label: "Top left" },
        ],
        default: "bottom-center",
      },
      {
        name: "format",
        label: "Format",
        type: "select",
        options: [
          { value: "number", label: "3" },
          { value: "number-of-total", label: "3 / 12" },
          { value: "page-x-of-y", label: "Page 3 of 12" },
        ],
        default: "number",
      },
    ],
  },
  crop: {
    title: "Crop PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "crop",
    endpoint: "crop",
    fields: [],
  },
  redact: {
    title: "Redact PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "redact",
    endpoint: "redact",
    fields: [],
  },
  "edit-pdf": {
    title: "Edit PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "edit-pdf",
    endpoint: "edit-pdf",
    fields: [],
  },
  sign: {
    title: "Sign PDF",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "sign",
    endpoint: "edit-pdf",
    fields: [],
  },
  "fill-form": {
    title: "PDF Forms",
    category: "Edit",
    multiFile: false,
    mode: "view",
    preview: "fill-form",
    endpoint: "fill-form",
    fields: [],
  },
  compress: {
    title: "Compress PDF",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    // Compression only re-encodes embedded images — it doesn't change how
    // a page looks, so there's nothing meaningful to show visually. The
    // page grid still renders (as input context); this note explains why
    // it looks identical before and after.
    previewNote: "Compression changes file size, not appearance — pages will look the same.",
    endpoint: "compress",
    fields: [
      { name: "image_quality", label: "Image quality", type: "range", min: 10, max: 100, default: 60 },
    ],
  },
  "to-images": {
    title: "PDF to Image",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "to-images",
    fields: [
      { name: "image_format", label: "Format", type: "select", options: ["jpg", "png"], default: "jpg" },
    ],
  },
  "to-word": {
    title: "PDF to Word",
    category: "Convert",
    multiFile: false,
    mode: "view",
    // A real preview would mean actually running the conversion — Word's
    // layout engine doesn't render in a browser, so there's no cheap way
    // to show this before committing. See the file's own note in the app.
    previewNote: "Word documents can't be previewed here — conversion quality depends on the PDF's layout.",
    endpoint: "to-word",
    fields: [],
  },
  "pdf-to-markdown": {
    title: "PDF to Markdown",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "pdf-to-markdown",
    previewNote: "PDF to Markdown extracts text and images — the result can't be previewed as a PDF page.",
    fields: [],
  },
  "pdf-to-pptx": {
    title: "PDF to PowerPoint",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "pdf-to-pptx",
    previewNote: "PDF to PowerPoint rebuilds positioned text boxes — complex layouts may not convert perfectly, and the result can't be previewed as a PDF page.",
    fields: [],
  },
  "pdf-to-xlsx": {
    title: "PDF to Excel",
    category: "Convert",
    multiFile: false,
    mode: "view",
    endpoint: "pdf-to-xlsx",
    previewNote: "PDF to Excel only includes pages with a detected table — the result can't be previewed as a PDF page.",
    fields: [],
  },
  "compare-pdf": {
    title: "Compare PDF",
    category: "Edit",
    fields: [],
  },
  repair: {
    title: "Repair PDF",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    endpoint: "repair",
    previewNote: "Repair fixes the file's internal structure, not its visual content — there's nothing meaningful to preview before running.",
    fields: [],
  },
  protect: {
    title: "Protect PDF",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    endpoint: "protect",
    fields: [{ name: "password", label: "Password", type: "password", default: "", maxLength: 127 }],
  },
  ocr: {
    title: "OCR PDF",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    endpoint: "ocr",
    previewNote: "OCR adds an invisible, searchable text layer to scanned pages — the page's appearance doesn't change, so there's nothing meaningful to preview before running.",
    fields: [
      {
        name: "languages",
        label: "Language(s)",
        type: "checkbox-group",
        required: true,
        options: [
          { value: "eng", label: "English" },
          { value: "spa", label: "Spanish" },
          { value: "fra", label: "French" },
          { value: "deu", label: "German" },
          { value: "por", label: "Portuguese" },
          { value: "chi_sim", label: "Chinese (Simplified)" },
          { value: "jpn", label: "Japanese" },
          { value: "ara", label: "Arabic" },
        ],
        default: ["eng"],
      },
      {
        name: "convert_to_pdfa",
        label: "Also convert to PDF/A",
        type: "checkbox",
        tooltip: "PDF/A is a locked-down archival format designed for long-term storage — every font is embedded and nothing depends on external files, so the document is guaranteed to open identically in the future. Useful for legal, medical, or government records; not needed for everyday use.",
        default: false,
      },
    ],
  },
  "pdf-to-pdfa": {
    title: "PDF to PDF/A",
    category: "Optimize",
    multiFile: false,
    mode: "view",
    endpoint: "pdf-to-pdfa",
    previewNote: "PDF/A converts the file's internal format for long-term archiving — it doesn't change how pages look, so there's nothing meaningful to preview before running.",
    fields: [],
  },
  "unlock-pdf": {
    title: "Unlock PDF",
    category: "Optimize",
    fields: [],
  },
  "images-to-pdf": {
    title: "Images to PDF",
    category: "Convert",
    multiFile: true,
    mode: "view",
    preview: "images-to-pdf",
    endpoint: "images-to-pdf",
    fileAccept: ".jpg,.jpeg,.png",
    fileTypeLabel: "image",
    filenameSuffix: "_combined",
    fields: [
      { name: "filename", label: "Output filename", type: "text", default: "" },
      {
        name: "fit_mode",
        label: "Fit mode",
        type: "select",
        options: [
          { value: "fit", label: "Fit (show the whole image)" },
          { value: "fill", label: "Fill (crop to fill the page)" },
        ],
        default: "fit",
      },
    ],
  },
};
